# Example configuration for VAMOS
data_dir: "./data"
results_dir: "./results"

mapping:
  alphafold_db: "./alphafold"

clustering:
  eps: 0.5
  min_samples: 5

ml:
  model: "random_forest"
  n_estimators: 100

stats:
  significance_level: 0.05
